package main

// generated by "/home/jsilva/projs/nurise/schematyper/__debug_bin --package=main --ptr-for-omit ./example/schema.json" -- DO NOT EDIT

type schema struct {
	Type int `json:"type,omitempty"`
}
